fixed bug which caused edges not to be created properly

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3941,8 +3941,8 @@ _ACEOF
   LIBS="-lz $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: zlib not found in $LD_PATH" >&5
-echo "$as_me: error: zlib not found in $LD_PATH" >&2;}
+  { { echo "$as_me:$LINENO: error: zlib not found" >&5
+echo "$as_me: error: zlib not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
